name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pipeline-microservice
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Print files
      run: |
        ls
